### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/uYouCompat#1]
I already install it but can't see any happened with original youtube ?

**Comment by PoomSmart** [comment]
Check the updated README.

**Comment by NguyenASang** [comment]
Does that mean you need to install uYou and then install this tweak to make uYou work on iOS 12 devices ?
How ?? I can't install uYou cuz it depends iOS 13 firmware.

**Comment by NguyenASang** [comment]
Do you have deb file of uYou 1.5 because that version was removed in his repo.
